Makefile update

diff --git a/.github/workflows/ci-pro.yml b/.github/workflows/ci-pro.yml
--- a/.github/workflows/ci-pro.yml
+++ b/.github/workflows/ci-pro.yml
@@ -13,7 +13,7 @@ on:
   
 jobs:
   integration-tests:
-    name: Run integration tests
+    name: Run integration tests and publish release candidate Docker image
     runs-on: ubuntu-latest
     steps:
       - name: Check out the repository
@@ -28,9 +28,28 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }} 
       - name: Publish the release candidate Docker image
-        run: make publish-image-rc             
+        run: make publish-image-rc     
+      #- name: Get latest Docker image version
+      #  id: get_version
+      #  run: |
+      #    version=$(curl -s 'https://registry.hub.docker.com/v2/repositories/your_docker_username/your_image_name/tags/' | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
+      #    echo "::set-output name=version::$version"  
+      #- name: Tag release with Docker version
+      #  if: success()
+      #  run: |
+      #    version=$(echo "${{ steps.get_version.outputs.version }}")
+      #    if [ -n "$version" ]; then
+      #      git config --local user.email "action@github.com"
+      #      git config --local user.name "GitHub Action"
+      #      git tag -a "v$version" -m "Version $version"
+      #      git push --tags
+      #    else
+      #      echo "Failed to retrieve version from Docker Hub."
+      #      exit 1
+      #    fi          
+
   publish-image:
-    name: Publish Docker image
+    name: Tag and publish the latest Docker image
     needs: integration-tests
     runs-on: ubuntu-latest
     steps:
@@ -40,6 +59,6 @@ jobs:
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}        
+          password: ${{ secrets.DOCKERHUB_TOKEN }}       
       - name: Publish the latest Docker image
         run: make publish-image-latest    
